// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package pggen

import (
	"context"
)

const getPasswordByEmail = `-- name: GetPasswordByEmail :many
SELECT key, value
FROM setting
WHERE key IN ('email', 'password')
`

type GetPasswordByEmailRow struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

func (q *Queries) GetPasswordByEmail(ctx context.Context) ([]GetPasswordByEmailRow, error) {
	rows, err := q.db.Query(ctx, getPasswordByEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPasswordByEmailRow
	for rows.Next() {
		var i GetPasswordByEmailRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
