// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM cart WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const getCart = `-- name: GetCart :one
SELECT id, customer_id, email, status, stripe_id, amount, created, updated
FROM cart WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCart(ctx context.Context, id string) (Cart, error) {
	row := q.db.QueryRow(ctx, getCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Email,
		&i.Status,
		&i.StripeID,
		&i.Amount,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const insertCart = `-- name: InsertCart :one
INSERT INTO cart (id, customer_id, email, status, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, email, status, stripe_id, amount, created, updated
`

type InsertCartParams struct {
	ID         string         `json:"id"`
	CustomerID *string        `json:"customer_id"`
	Email      *string        `json:"email"`
	Status     string         `json:"status"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) InsertCart(ctx context.Context, arg InsertCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, insertCart,
		arg.ID,
		arg.CustomerID,
		arg.Email,
		arg.Status,
		arg.Amount,
	)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Email,
		&i.Status,
		&i.StripeID,
		&i.Amount,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateCart = `-- name: UpdateCart :exec
UPDATE cart SET customer_id = $1, email = $2, status = $3, amount = $4, updated = CURRENT_TIMESTAMP
WHERE id = $5
`

type UpdateCartParams struct {
	CustomerID *string        `json:"customer_id"`
	Email      *string        `json:"email"`
	Status     string         `json:"status"`
	Amount     pgtype.Numeric `json:"amount"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateCart(ctx context.Context, arg UpdateCartParams) error {
	_, err := q.db.Exec(ctx, updateCart,
		arg.CustomerID,
		arg.Email,
		arg.Status,
		arg.Amount,
		arg.ID,
	)
	return err
}
