// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePage = `-- name: DeletePage :exec
DELETE FROM page WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, name, slug, position, content, active, created, updated
FROM page
WHERE id = $1
LIMIT 1
`

type GetPageByIDRow struct {
	ID       string           `json:"id"`
	Name     string           `json:"name"`
	Slug     string           `json:"slug"`
	Position string           `json:"position"`
	Content  *string          `json:"content"`
	Active   bool             `json:"active"`
	Created  pgtype.Timestamp `json:"created"`
	Updated  pgtype.Timestamp `json:"updated"`
}

func (q *Queries) GetPageByID(ctx context.Context, id string) (GetPageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i GetPageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Position,
		&i.Content,
		&i.Active,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, name, slug, position, content, active, created, updated
FROM page
WHERE slug = $1
LIMIT 1
`

type GetPageBySlugRow struct {
	ID       string           `json:"id"`
	Name     string           `json:"name"`
	Slug     string           `json:"slug"`
	Position string           `json:"position"`
	Content  *string          `json:"content"`
	Active   bool             `json:"active"`
	Created  pgtype.Timestamp `json:"created"`
	Updated  pgtype.Timestamp `json:"updated"`
}

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (GetPageBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPageBySlug, slug)
	var i GetPageBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Position,
		&i.Content,
		&i.Active,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const insertPage = `-- name: InsertPage :one
INSERT INTO page (id, name, slug, position, content, active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, position, content, active, created, updated
`

type InsertPageParams struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Slug     string  `json:"slug"`
	Position string  `json:"position"`
	Content  *string `json:"content"`
	Active   bool    `json:"active"`
}

type InsertPageRow struct {
	ID       string           `json:"id"`
	Name     string           `json:"name"`
	Slug     string           `json:"slug"`
	Position string           `json:"position"`
	Content  *string          `json:"content"`
	Active   bool             `json:"active"`
	Created  pgtype.Timestamp `json:"created"`
	Updated  pgtype.Timestamp `json:"updated"`
}

func (q *Queries) InsertPage(ctx context.Context, arg InsertPageParams) (InsertPageRow, error) {
	row := q.db.QueryRow(ctx, insertPage,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Position,
		arg.Content,
		arg.Active,
	)
	var i InsertPageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Position,
		&i.Content,
		&i.Active,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const pageExists = `-- name: PageExists :one
SELECT EXISTS(SELECT 1 FROM page WHERE slug = $1)
`

func (q *Queries) PageExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, pageExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePage = `-- name: UpdatePage :exec
UPDATE page
SET name = $1, slug = $2, position = $3, content = $4, active = $5, updated = CURRENT_TIMESTAMP
WHERE id = $6
`

type UpdatePageParams struct {
	Name     string  `json:"name"`
	Slug     string  `json:"slug"`
	Position string  `json:"position"`
	Content  *string `json:"content"`
	Active   bool    `json:"active"`
	ID       string  `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.Exec(ctx, updatePage,
		arg.Name,
		arg.Slug,
		arg.Position,
		arg.Content,
		arg.Active,
		arg.ID,
	)
	return err
}

const updatePageActive = `-- name: UpdatePageActive :exec
UPDATE page
SET active = NOT active, updated = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdatePageActive(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updatePageActive, id)
	return err
}
