// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package pggen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE product
SET deleted = TRUE, updated = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, "desc", slug, amount, digital, active, deleted, created, updated
FROM product
WHERE id = $1 AND deleted = FALSE
LIMIT 1
`

type GetProductRow struct {
	ID      string           `json:"id"`
	Name    string           `json:"name"`
	Desc    string           `json:"desc"`
	Slug    string           `json:"slug"`
	Amount  pgtype.Numeric   `json:"amount"`
	Digital *string          `json:"digital"`
	Active  bool             `json:"active"`
	Deleted bool             `json:"deleted"`
	Created pgtype.Timestamp `json:"created"`
	Updated pgtype.Timestamp `json:"updated"`
}

func (q *Queries) GetProduct(ctx context.Context, id string) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO product (id, name, "desc", slug, amount, digital, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, "desc", slug, amount, digital, active, deleted, created, updated
`

type InsertProductParams struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Desc    string         `json:"desc"`
	Slug    string         `json:"slug"`
	Amount  pgtype.Numeric `json:"amount"`
	Digital *string        `json:"digital"`
	Active  bool           `json:"active"`
}

type InsertProductRow struct {
	ID      string           `json:"id"`
	Name    string           `json:"name"`
	Desc    string           `json:"desc"`
	Slug    string           `json:"slug"`
	Amount  pgtype.Numeric   `json:"amount"`
	Digital *string          `json:"digital"`
	Active  bool             `json:"active"`
	Deleted bool             `json:"deleted"`
	Created pgtype.Timestamp `json:"created"`
	Updated pgtype.Timestamp `json:"updated"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (InsertProductRow, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.ID,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Digital,
		arg.Active,
	)
	var i InsertProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS(SELECT 1 FROM product WHERE slug = $1 AND deleted = FALSE)
`

func (q *Queries) ProductExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, productExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product
SET name = $1, "desc" = $2, slug = $3, amount = $4, digital = $5, active = $6, updated = CURRENT_TIMESTAMP
WHERE id = $7
`

type UpdateProductParams struct {
	Name    string         `json:"name"`
	Desc    string         `json:"desc"`
	Slug    string         `json:"slug"`
	Amount  pgtype.Numeric `json:"amount"`
	Digital *string        `json:"digital"`
	Active  bool           `json:"active"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Digital,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateProductActive = `-- name: UpdateProductActive :exec
UPDATE product
SET active = NOT active, updated = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateProductActive(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateProductActive, id)
	return err
}
