// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pggen

import (
	"context"
)

type Querier interface {
	CleanupExpiredSessions(ctx context.Context, arg CleanupExpiredSessionsParams) error
	DeleteCart(ctx context.Context, id string) error
	DeleteCustomer(ctx context.Context, id string) error
	DeletePage(ctx context.Context, id string) error
	DeleteProduct(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, key string) error
	GetCart(ctx context.Context, id string) (Cart, error)
	GetCustomer(ctx context.Context, id string) (Customer, error)
	GetPageByID(ctx context.Context, id string) (GetPageByIDRow, error)
	GetPageBySlug(ctx context.Context, slug string) (GetPageBySlugRow, error)
	GetPasswordByEmail(ctx context.Context) ([]GetPasswordByEmailRow, error)
	GetProduct(ctx context.Context, id string) (GetProductRow, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetSettingValue(ctx context.Context, key string) (*string, error)
	InsertCart(ctx context.Context, arg InsertCartParams) (Cart, error)
	InsertCustomer(ctx context.Context, arg InsertCustomerParams) (Customer, error)
	InsertPage(ctx context.Context, arg InsertPageParams) (InsertPageRow, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (InsertProductRow, error)
	PageExists(ctx context.Context, slug string) (bool, error)
	ProductExists(ctx context.Context, slug string) (bool, error)
	UpdateCart(ctx context.Context, arg UpdateCartParams) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
	UpdatePage(ctx context.Context, arg UpdatePageParams) error
	UpdatePageActive(ctx context.Context, id string) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductActive(ctx context.Context, id string) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateSettingValue(ctx context.Context, arg UpdateSettingValueParams) error
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
}

var _ Querier = (*Queries)(nil)
