// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package pggen

import (
	"context"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM session
WHERE expires < $1 AND key != $2
`

type CleanupExpiredSessionsParams struct {
	Expires *int32 `json:"expires"`
	Key     string `json:"key"`
}

func (q *Queries) CleanupExpiredSessions(ctx context.Context, arg CleanupExpiredSessionsParams) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions, arg.Expires, arg.Key)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE key = $1
`

func (q *Queries) DeleteSession(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSession, key)
	return err
}

const getSession = `-- name: GetSession :one
SELECT key, value, expires
FROM session
WHERE key = $1 AND expires > $2
LIMIT 1
`

type GetSessionParams struct {
	Key     string `json:"key"`
	Expires *int32 `json:"expires"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.Key, arg.Expires)
	var i Session
	err := row.Scan(&i.Key, &i.Value, &i.Expires)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE session
SET value = $1, expires = $2
WHERE key = $3
`

type UpdateSessionParams struct {
	Value   *string `json:"value"`
	Expires *int32  `json:"expires"`
	Key     string  `json:"key"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession, arg.Value, arg.Expires, arg.Key)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO session (key, value, expires)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, expires = EXCLUDED.expires
`

type UpsertSessionParams struct {
	Key     string  `json:"key"`
	Value   *string `json:"value"`
	Expires *int32  `json:"expires"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.Exec(ctx, upsertSession, arg.Key, arg.Value, arg.Expires)
	return err
}
