version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  groups:
    go-dependencies:
      patterns:
        - "*"
  commit-message:
    prefix: "🔧 build"
    include: "scope"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  groups:
    github-actions:
      patterns:
        - "*"
  commit-message:
    prefix: "🔧 build"
    include: "scope"

- package-ecosystem: "npm"
  directory: "/web/admin"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  groups:
    npm-admin:
      patterns:
        - "*"
  commit-message:
    prefix: "🔧 build"
    include: "scope"

- package-ecosystem: "npm"
  directory: "/web/site"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  groups:
    npm-site:
      patterns:
        - "*"
  commit-message:
    prefix: "🔧 build"
    include: "scope"

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  groups:
    npm-root:
      patterns:
        - "*"
  commit-message:
    prefix: "🔧 build"
    include: "scope"
