version: 2

before:
  hooks:
    - go mod tidy
    - go mod download
    - sh -c "cd web/admin && bun install --force"
    - sh -c "cd web/admin && bun run build"
    - sh -c "cd web/site && bun install --force"
    - sh -c "cd web/site && bun run build"

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "main.version=v{{.Version}}"
      - -X "main.gitCommit={{.ShortCommit}}"
      - -X "main.buildDate={{.Now.Format "2006-01-02"}}"
    main: ./cmd/main.go
    binary: mycart

archives:
  - name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - init
      - '^.*?ci:'
      - '^.*?test:'
      - '^.*?build(deps):'
      - '^.*?build:'
      - 'README'
      - 'Up'
      - 'merge conflict'
      - Bump
      - Small fix
      - Update
      - Updating
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: 'Build process updates'
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

release:
  name_template: "v{{ .Version }}"
  header: |
    > *To update the prebuilt executable you can run `./mycart update`*

  footer: |
    **Full Changelog**: https://github.com/shurco/mycart/compare/{{ .PreviousTag }}...{{ .Tag }}

    > [!WARNING]
    > If you are updating, it is essential to do the following - back up the **./site** folder if you have made changes to it (you can rename it). A new folder with updated files will be created.
