command = "/usr/local/bin/mycart-wrapper.sh"
start-delay = "2s"
start-after = []
working-directory = "/app"
stdout = "/logs/mycart-stdout.log"
stderr = "/logs/mycart-stderr.log"

[restart]
strategy = "always"
backoff = "10s"
attempts = 0

[environment]

[healthiness]
http-endpoint = "http://127.0.0.1:80/health"

[termination]
signal = "TERM"
wait = "10s"
