command = "/usr/local/bin/xmpp-proxy-wrapper.sh"
start-delay = "5s"
start-after = ["mycart.toml"]
working-directory = "/etc/xmpp-proxy"
stdout = "/logs/xmpp-proxy-stdout.log"
stderr = "/logs/xmpp-proxy-stderr.log"
pass-environment = ["XMPP_DOMAIN", "XMPP_PROXY_PROSODY_C2S", "XMPP_PROXY_PROSODY_S2S"]

[restart]
strategy = "always"
backoff = "10s"
attempts = 0

[environment]
RUST_LOG = "info"

[termination]
signal = "TERM"
wait = "15s"
