// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: new_carts.sql

package postgres

import (
	"context"
	"database/sql"
)

const createCartItem = `-- name: CreateCartItem :exec
INSERT INTO cart_items (id, cart_id, product_id, quantity, price, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCartItemParams struct {
	ID        string       `json:"id"`
	CartID    string       `json:"cart_id"`
	ProductID string       `json:"product_id"`
	Quantity  int32        `json:"quantity"`
	Price     string       `json:"price"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) error {
	_, err := q.exec(ctx, q.createCartItemStmt, createCartItem,
		arg.ID,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.CreatedAt,
	)
	return err
}

const createNewCart = `-- name: CreateNewCart :exec
INSERT INTO new_carts (id, session_id, status, total, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateNewCartParams struct {
	ID        string       `json:"id"`
	SessionID string       `json:"session_id"`
	Status    string       `json:"status"`
	Total     string       `json:"total"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateNewCart(ctx context.Context, arg CreateNewCartParams) error {
	_, err := q.exec(ctx, q.createNewCartStmt, createNewCart,
		arg.ID,
		arg.SessionID,
		arg.Status,
		arg.Total,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteCartItemStmt, deleteCartItem, id)
	return err
}

const deleteCartItemsByCartID = `-- name: DeleteCartItemsByCartID :exec
DELETE FROM cart_items WHERE cart_id = $1
`

func (q *Queries) DeleteCartItemsByCartID(ctx context.Context, cartID string) error {
	_, err := q.exec(ctx, q.deleteCartItemsByCartIDStmt, deleteCartItemsByCartID, cartID)
	return err
}

const deleteNewCart = `-- name: DeleteNewCart :exec
DELETE FROM new_carts WHERE id = $1
`

func (q *Queries) DeleteNewCart(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteNewCartStmt, deleteNewCart, id)
	return err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, cart_id, product_id, quantity, price, created_at
FROM cart_items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCartItem(ctx context.Context, id string) (CartItem, error) {
	row := q.queryRow(ctx, q.getCartItemStmt, getCartItem, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const getNewCartByID = `-- name: GetNewCartByID :one
SELECT id, session_id, status, total, created_at, updated_at
FROM new_carts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetNewCartByID(ctx context.Context, id string) (NewCart, error) {
	row := q.queryRow(ctx, q.getNewCartByIDStmt, getNewCartByID, id)
	var i NewCart
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewCartBySessionID = `-- name: GetNewCartBySessionID :one
SELECT id, session_id, status, total, created_at, updated_at
FROM new_carts
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetNewCartBySessionID(ctx context.Context, sessionID string) (NewCart, error) {
	row := q.queryRow(ctx, q.getNewCartBySessionIDStmt, getNewCartBySessionID, sessionID)
	var i NewCart
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.Total,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, cart_id, product_id, quantity, price, created_at
FROM cart_items
WHERE cart_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCartItems(ctx context.Context, cartID string) ([]CartItem, error) {
	rows, err := q.query(ctx, q.listCartItemsStmt, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItem = `-- name: UpdateCartItem :exec
UPDATE cart_items
SET quantity = $1, price = $2
WHERE id = $3
`

type UpdateCartItemParams struct {
	Quantity int32  `json:"quantity"`
	Price    string `json:"price"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) error {
	_, err := q.exec(ctx, q.updateCartItemStmt, updateCartItem, arg.Quantity, arg.Price, arg.ID)
	return err
}

const updateNewCart = `-- name: UpdateNewCart :exec
UPDATE new_carts
SET status = $1, total = $2, updated_at = $3
WHERE id = $4
`

type UpdateNewCartParams struct {
	Status    string       `json:"status"`
	Total     string       `json:"total"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdateNewCart(ctx context.Context, arg UpdateNewCartParams) error {
	_, err := q.exec(ctx, q.updateNewCartStmt, updateNewCart,
		arg.Status,
		arg.Total,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
