// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
)

const bulkDeleteProductImages = `-- name: BulkDeleteProductImages :exec

DELETE FROM product_image
WHERE product_id = $1
`

// Advanced Product Queries
func (q *Queries) BulkDeleteProductImages(ctx context.Context, productID string) error {
	_, err := q.exec(ctx, q.bulkDeleteProductImagesStmt, bulkDeleteProductImages, productID)
	return err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM product WHERE deleted = FALSE
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countProductsStmt, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (id, name, brief, "desc", slug, amount, metadata, attribute, digital, active, has_variants, quantity, sku, seo, created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW())
RETURNING id, name, brief, "desc", slug, amount, metadata, attribute, digital, active, has_variants, quantity, sku, seo, deleted, EXTRACT(EPOCH FROM created)::bigint as created, updated
`

type CreateProductParams struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Brief       string          `json:"brief"`
	Desc        string          `json:"desc"`
	Slug        string          `json:"slug"`
	Amount      string          `json:"amount"`
	Metadata    json.RawMessage `json:"metadata"`
	Attribute   json.RawMessage `json:"attribute"`
	Digital     sql.NullString  `json:"digital"`
	Active      bool            `json:"active"`
	HasVariants sql.NullBool    `json:"has_variants"`
	Quantity    sql.NullInt32   `json:"quantity"`
	Sku         sql.NullString  `json:"sku"`
	Seo         json.RawMessage `json:"seo"`
}

type CreateProductRow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Brief       string          `json:"brief"`
	Desc        string          `json:"desc"`
	Slug        string          `json:"slug"`
	Amount      string          `json:"amount"`
	Metadata    json.RawMessage `json:"metadata"`
	Attribute   json.RawMessage `json:"attribute"`
	Digital     sql.NullString  `json:"digital"`
	Active      bool            `json:"active"`
	HasVariants sql.NullBool    `json:"has_variants"`
	Quantity    sql.NullInt32   `json:"quantity"`
	Sku         sql.NullString  `json:"sku"`
	Seo         json.RawMessage `json:"seo"`
	Deleted     bool            `json:"deleted"`
	Created     int64           `json:"created"`
	Updated     sql.NullTime    `json:"updated"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.ID,
		arg.Name,
		arg.Brief,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Metadata,
		arg.Attribute,
		arg.Digital,
		arg.Active,
		arg.HasVariants,
		arg.Quantity,
		arg.Sku,
		arg.Seo,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brief,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.HasVariants,
		&i.Quantity,
		&i.Sku,
		&i.Seo,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createProductOption = `-- name: CreateProductOption :one
INSERT INTO product_option (id, name, product_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, name, product_id, position, created
`

type CreateProductOptionParams struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	ProductID string        `json:"product_id"`
	Position  sql.NullInt32 `json:"position"`
}

type CreateProductOptionRow struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	ProductID string        `json:"product_id"`
	Position  sql.NullInt32 `json:"position"`
	Created   sql.NullTime  `json:"created"`
}

func (q *Queries) CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (CreateProductOptionRow, error) {
	row := q.queryRow(ctx, q.createProductOptionStmt, createProductOption,
		arg.ID,
		arg.Name,
		arg.ProductID,
		arg.Position,
	)
	var i CreateProductOptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProductID,
		&i.Position,
		&i.Created,
	)
	return i, err
}

const createProductOptionValue = `-- name: CreateProductOptionValue :one
INSERT INTO product_option_value (id, option_id, value, position)
VALUES ($1, $2, $3, $4)
RETURNING id, option_id, value, position
`

type CreateProductOptionValueParams struct {
	ID       string        `json:"id"`
	OptionID string        `json:"option_id"`
	Value    string        `json:"value"`
	Position sql.NullInt32 `json:"position"`
}

func (q *Queries) CreateProductOptionValue(ctx context.Context, arg CreateProductOptionValueParams) (ProductOptionValue, error) {
	row := q.queryRow(ctx, q.createProductOptionValueStmt, createProductOptionValue,
		arg.ID,
		arg.OptionID,
		arg.Value,
		arg.Position,
	)
	var i ProductOptionValue
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.Value,
		&i.Position,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variant (id, product_id, sku, price_surcharge, quantity, option_values)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, sku, price_surcharge, quantity, option_values, active, deleted, created, updated
`

type CreateProductVariantParams struct {
	ID             string         `json:"id"`
	ProductID      string         `json:"product_id"`
	Sku            sql.NullString `json:"sku"`
	PriceSurcharge sql.NullString `json:"price_surcharge"`
	Quantity       sql.NullInt32  `json:"quantity"`
	OptionValues   string         `json:"option_values"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.queryRow(ctx, q.createProductVariantStmt, createProductVariant,
		arg.ID,
		arg.ProductID,
		arg.Sku,
		arg.PriceSurcharge,
		arg.Quantity,
		arg.OptionValues,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.PriceSurcharge,
		&i.Quantity,
		&i.OptionValues,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductStmt, deleteProduct, id)
	return err
}

const deleteProductOption = `-- name: DeleteProductOption :exec
DELETE FROM product_option WHERE id = $1
`

func (q *Queries) DeleteProductOption(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductOptionStmt, deleteProductOption, id)
	return err
}

const deleteProductOptionValue = `-- name: DeleteProductOptionValue :exec
DELETE FROM product_option_value WHERE id = $1
`

func (q *Queries) DeleteProductOptionValue(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductOptionValueStmt, deleteProductOptionValue, id)
	return err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variant WHERE id = $1
`

func (q *Queries) DeleteProductVariant(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductVariantStmt, deleteProductVariant, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product WHERE id = $1 AND deleted = FALSE LIMIT 1
`

type GetProductByIDRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) GetProductByID(ctx context.Context, id string) (GetProductByIDRow, error) {
	row := q.queryRow(ctx, q.getProductByIDStmt, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product WHERE slug = $1 AND deleted = FALSE LIMIT 1
`

type GetProductBySlugRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.queryRow(ctx, q.getProductBySlugStmt, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductDetailByID = `-- name: GetProductDetailByID :one
SELECT DISTINCT
  p.id,
  p.name,
  p.brief,
  p.desc,
  p.slug,
  p.amount,
  p.quantity,
  p.sku,
  p.has_variants,
  p.active,
  p.metadata,
  p.attribute,
  p.digital,
  p.seo,
  jsonb_agg(jsonb_build_object('id', pi.id, 'name', pi.name, 'ext', pi.ext)) as images,
  EXISTS(SELECT 1 FROM digital_data WHERE digital_data.product_id = p.id AND digital_data.cart_id IS NULL) OR
  EXISTS(SELECT 1 FROM digital_file WHERE digital_file.product_id = p.id) AS digital_filled,
  EXTRACT(EPOCH FROM p.created)::bigint as created,
  EXTRACT(EPOCH FROM p.updated)::bigint as updated
FROM product p
LEFT JOIN product_image pi ON p.id = pi.product_id
WHERE p.id = $1
GROUP BY p.id, p.name, p.brief, p.desc, p.slug, p.amount, p.quantity, p.sku, p.has_variants, p.active, p.metadata, p.attribute, p.digital, p.seo, p.created, p.updated
`

type GetProductDetailByIDRow struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Brief         string          `json:"brief"`
	Desc          string          `json:"desc"`
	Slug          string          `json:"slug"`
	Amount        string          `json:"amount"`
	Quantity      sql.NullInt32   `json:"quantity"`
	Sku           sql.NullString  `json:"sku"`
	HasVariants   sql.NullBool    `json:"has_variants"`
	Active        bool            `json:"active"`
	Metadata      json.RawMessage `json:"metadata"`
	Attribute     json.RawMessage `json:"attribute"`
	Digital       sql.NullString  `json:"digital"`
	Seo           json.RawMessage `json:"seo"`
	Images        json.RawMessage `json:"images"`
	DigitalFilled sql.NullBool    `json:"digital_filled"`
	Created       int64           `json:"created"`
	Updated       int64           `json:"updated"`
}

func (q *Queries) GetProductDetailByID(ctx context.Context, id string) (GetProductDetailByIDRow, error) {
	row := q.queryRow(ctx, q.getProductDetailByIDStmt, getProductDetailByID, id)
	var i GetProductDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brief,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Quantity,
		&i.Sku,
		&i.HasVariants,
		&i.Active,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Seo,
		&i.Images,
		&i.DigitalFilled,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductDetailBySlug = `-- name: GetProductDetailBySlug :one
SELECT DISTINCT
  p.id,
  p.name,
  p.brief,
  p.desc,
  p.slug,
  p.amount,
  p.quantity,
  p.sku,
  p.has_variants,
  p.active,
  p.metadata,
  p.attribute,
  p.digital,
  p.seo,
  jsonb_agg(jsonb_build_object('id', pi.id, 'name', pi.name, 'ext', pi.ext)) as images,
  EXTRACT(EPOCH FROM p.created)::bigint as created,
  EXTRACT(EPOCH FROM p.updated)::bigint as updated
FROM product p
LEFT JOIN product_image pi ON p.id = pi.product_id
WHERE p.slug = $1 AND p.deleted = FALSE AND p.active = TRUE
GROUP BY p.id, p.name, p.brief, p.desc, p.slug, p.amount, p.quantity, p.sku, p.has_variants, p.active, p.metadata, p.attribute, p.digital, p.seo, p.created, p.updated
`

type GetProductDetailBySlugRow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Brief       string          `json:"brief"`
	Desc        string          `json:"desc"`
	Slug        string          `json:"slug"`
	Amount      string          `json:"amount"`
	Quantity    sql.NullInt32   `json:"quantity"`
	Sku         sql.NullString  `json:"sku"`
	HasVariants sql.NullBool    `json:"has_variants"`
	Active      bool            `json:"active"`
	Metadata    json.RawMessage `json:"metadata"`
	Attribute   json.RawMessage `json:"attribute"`
	Digital     sql.NullString  `json:"digital"`
	Seo         json.RawMessage `json:"seo"`
	Images      json.RawMessage `json:"images"`
	Created     int64           `json:"created"`
	Updated     int64           `json:"updated"`
}

func (q *Queries) GetProductDetailBySlug(ctx context.Context, slug string) (GetProductDetailBySlugRow, error) {
	row := q.queryRow(ctx, q.getProductDetailBySlugStmt, getProductDetailBySlug, slug)
	var i GetProductDetailBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brief,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Quantity,
		&i.Sku,
		&i.HasVariants,
		&i.Active,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Seo,
		&i.Images,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductDigitalContent = `-- name: GetProductDigitalContent :many
SELECT
    p.digital,
    df.id as file_id,
    df.name as file_name,
    df.ext as file_ext,
    dd.id as data_id,
    dd.content as data_content,
    dd.cart_id as data_cart_id
FROM product p
LEFT JOIN digital_file df ON p.id = df.product_id
LEFT JOIN digital_data dd ON p.id = dd.product_id
WHERE p.id = $1
`

type GetProductDigitalContentRow struct {
	Digital     sql.NullString `json:"digital"`
	FileID      sql.NullString `json:"file_id"`
	FileName    sql.NullString `json:"file_name"`
	FileExt     sql.NullString `json:"file_ext"`
	DataID      sql.NullString `json:"data_id"`
	DataContent sql.NullString `json:"data_content"`
	DataCartID  sql.NullString `json:"data_cart_id"`
}

func (q *Queries) GetProductDigitalContent(ctx context.Context, id string) ([]GetProductDigitalContentRow, error) {
	rows, err := q.query(ctx, q.getProductDigitalContentStmt, getProductDigitalContent, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductDigitalContentRow{}
	for rows.Next() {
		var i GetProductDigitalContentRow
		if err := rows.Scan(
			&i.Digital,
			&i.FileID,
			&i.FileName,
			&i.FileExt,
			&i.DataID,
			&i.DataContent,
			&i.DataCartID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductOption = `-- name: GetProductOption :one
SELECT id, name, product_id, position, created
FROM product_option
WHERE id = $1 LIMIT 1
`

type GetProductOptionRow struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	ProductID string        `json:"product_id"`
	Position  sql.NullInt32 `json:"position"`
	Created   sql.NullTime  `json:"created"`
}

func (q *Queries) GetProductOption(ctx context.Context, id string) (GetProductOptionRow, error) {
	row := q.queryRow(ctx, q.getProductOptionStmt, getProductOption, id)
	var i GetProductOptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProductID,
		&i.Position,
		&i.Created,
	)
	return i, err
}

const getProductWithVariants = `-- name: GetProductWithVariants :many

SELECT
    p.id as product_id,
    p.name as product_name,
    pv.id as variant_id,
    pv.sku as variant_sku,
    pv.price_surcharge as variant_price_surcharge,
    pv.quantity as variant_quantity,
    pv.option_values as variant_option_values
FROM product p
LEFT JOIN product_variant pv ON p.id = pv.product_id
WHERE p.id = $1
`

type GetProductWithVariantsRow struct {
	ProductID             string         `json:"product_id"`
	ProductName           string         `json:"product_name"`
	VariantID             sql.NullString `json:"variant_id"`
	VariantSku            sql.NullString `json:"variant_sku"`
	VariantPriceSurcharge sql.NullString `json:"variant_price_surcharge"`
	VariantQuantity       sql.NullInt32  `json:"variant_quantity"`
	VariantOptionValues   sql.NullString `json:"variant_option_values"`
}

// Product Variant Queries
func (q *Queries) GetProductWithVariants(ctx context.Context, id string) ([]GetProductWithVariantsRow, error) {
	rows, err := q.query(ctx, q.getProductWithVariantsStmt, getProductWithVariants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductWithVariantsRow{}
	for rows.Next() {
		var i GetProductWithVariantsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.VariantID,
			&i.VariantSku,
			&i.VariantPriceSurcharge,
			&i.VariantQuantity,
			&i.VariantOptionValues,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithImages = `-- name: GetProductsWithImages :many
SELECT
    p.id as product_id,
    p.name as product_name,
    pi.id as image_id,
    pi.name as image_name,
    pi.ext as image_ext
FROM product p
LEFT JOIN product_image pi ON p.id = pi.product_id
WHERE p.active = TRUE AND p.deleted = FALSE
ORDER BY p.created DESC
`

type GetProductsWithImagesRow struct {
	ProductID   string         `json:"product_id"`
	ProductName string         `json:"product_name"`
	ImageID     sql.NullString `json:"image_id"`
	ImageName   sql.NullString `json:"image_name"`
	ImageExt    sql.NullString `json:"image_ext"`
}

func (q *Queries) GetProductsWithImages(ctx context.Context) ([]GetProductsWithImagesRow, error) {
	rows, err := q.query(ctx, q.getProductsWithImagesStmt, getProductsWithImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsWithImagesRow{}
	for rows.Next() {
		var i GetProductsWithImagesRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.ImageID,
			&i.ImageName,
			&i.ImageExt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE active = TRUE AND deleted = FALSE
ORDER BY created DESC
LIMIT $1 OFFSET $2
`

type ListActiveProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListActiveProductsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]ListActiveProductsRow, error) {
	rows, err := q.query(ctx, q.listActiveProductsStmt, listActiveProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsRow{}
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product ORDER BY created
`

type ListAllProductsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) ListAllProducts(ctx context.Context) ([]ListAllProductsRow, error) {
	rows, err := q.query(ctx, q.listAllProductsStmt, listAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProductsRow{}
	for rows.Next() {
		var i ListAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductOptionValuesByOption = `-- name: ListProductOptionValuesByOption :many
SELECT id, option_id, value, position
FROM product_option_value
WHERE option_id = $1
ORDER BY position
`

func (q *Queries) ListProductOptionValuesByOption(ctx context.Context, optionID string) ([]ProductOptionValue, error) {
	rows, err := q.query(ctx, q.listProductOptionValuesByOptionStmt, listProductOptionValuesByOption, optionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOptionValue{}
	for rows.Next() {
		var i ProductOptionValue
		if err := rows.Scan(
			&i.ID,
			&i.OptionID,
			&i.Value,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductOptionsByProduct = `-- name: ListProductOptionsByProduct :many
SELECT id, name, product_id, position, created
FROM product_option
WHERE product_id = $1
ORDER BY position
`

type ListProductOptionsByProductRow struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	ProductID string        `json:"product_id"`
	Position  sql.NullInt32 `json:"position"`
	Created   sql.NullTime  `json:"created"`
}

func (q *Queries) ListProductOptionsByProduct(ctx context.Context, productID string) ([]ListProductOptionsByProductRow, error) {
	rows, err := q.query(ctx, q.listProductOptionsByProductStmt, listProductOptionsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductOptionsByProductRow{}
	for rows.Next() {
		var i ListProductOptionsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProductID,
			&i.Position,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsByProduct = `-- name: ListProductVariantsByProduct :many
SELECT id, product_id, sku, price_surcharge, quantity, option_values, active, deleted, created, updated
FROM product_variant
WHERE product_id = $1
`

func (q *Queries) ListProductVariantsByProduct(ctx context.Context, productID string) ([]ProductVariant, error) {
	rows, err := q.query(ctx, q.listProductVariantsByProductStmt, listProductVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.PriceSurcharge,
			&i.Quantity,
			&i.OptionValues,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE deleted = FALSE
ORDER BY created DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.query(ctx, q.listProductsStmt, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPrivate = `-- name: ListProductsPrivate :many
SELECT DISTINCT
  p.id,
  p.name,
  p.brief,
  p.slug,
  p.amount,
  p.quantity,
  p.has_variants,
  p.active,
  p.digital,
  EXISTS(SELECT 1 FROM digital_data WHERE digital_data.product_id = p.id AND digital_data.cart_id IS NULL) OR
  EXISTS(SELECT 1 FROM digital_file WHERE digital_file.product_id = p.id) AS digital_filled,
  (SELECT jsonb_agg(jsonb_build_object('id', product_image.id, 'name', product_image.name, 'ext', product_image.ext))
   FROM product_image WHERE product_id = p.id LIMIT 1) as image,
  (SELECT jsonb_agg(jsonb_build_object('id', pv.id, 'sku', pv.sku, 'quantity', pv.quantity, 'price_surcharge', pv.price_surcharge, 'option_values', pv.option_values::jsonb, 'active', CASE WHEN pv.active THEN 'true'::jsonb ELSE 'false'::jsonb END))
   FROM product_variant pv WHERE pv.product_id = p.id) as variants,
  EXTRACT(EPOCH FROM p.created)::bigint as created
FROM product p
WHERE p.deleted = FALSE
LIMIT $1 OFFSET $2
`

type ListProductsPrivateParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsPrivateRow struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Brief         string          `json:"brief"`
	Slug          string          `json:"slug"`
	Amount        string          `json:"amount"`
	Quantity      sql.NullInt32   `json:"quantity"`
	HasVariants   sql.NullBool    `json:"has_variants"`
	Active        bool            `json:"active"`
	Digital       sql.NullString  `json:"digital"`
	DigitalFilled sql.NullBool    `json:"digital_filled"`
	Image         json.RawMessage `json:"image"`
	Variants      json.RawMessage `json:"variants"`
	Created       int64           `json:"created"`
}

func (q *Queries) ListProductsPrivate(ctx context.Context, arg ListProductsPrivateParams) ([]ListProductsPrivateRow, error) {
	rows, err := q.query(ctx, q.listProductsPrivateStmt, listProductsPrivate, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsPrivateRow{}
	for rows.Next() {
		var i ListProductsPrivateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brief,
			&i.Slug,
			&i.Amount,
			&i.Quantity,
			&i.HasVariants,
			&i.Active,
			&i.Digital,
			&i.DigitalFilled,
			&i.Image,
			&i.Variants,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPublic = `-- name: ListProductsPublic :many
SELECT DISTINCT
  p.id,
  p.name,
  p.brief,
  p.slug,
  p.amount,
  p.quantity,
  p.has_variants,
  p.active,
  p.digital,
  EXISTS(SELECT 1 FROM digital_data WHERE digital_data.product_id = p.id AND digital_data.cart_id IS NULL) OR
  EXISTS(SELECT 1 FROM digital_file WHERE digital_file.product_id = p.id) AS digital_filled,
  (SELECT jsonb_agg(jsonb_build_object('id', product_image.id, 'name', product_image.name, 'ext', product_image.ext))
   FROM product_image WHERE product_id = p.id LIMIT 1) as image,
  (SELECT jsonb_agg(jsonb_build_object('id', pv.id, 'sku', pv.sku, 'quantity', pv.quantity, 'price_surcharge', pv.price_surcharge, 'option_values', pv.option_values::jsonb, 'active', CASE WHEN pv.active THEN 'true'::jsonb ELSE 'false'::jsonb END))
   FROM product_variant pv WHERE pv.product_id = p.id AND pv.active = TRUE) as variants,
  EXTRACT(EPOCH FROM p.created)::bigint as created
FROM product p
WHERE p.deleted = FALSE AND p.active = TRUE
LIMIT $1 OFFSET $2
`

type ListProductsPublicParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsPublicRow struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Brief         string          `json:"brief"`
	Slug          string          `json:"slug"`
	Amount        string          `json:"amount"`
	Quantity      sql.NullInt32   `json:"quantity"`
	HasVariants   sql.NullBool    `json:"has_variants"`
	Active        bool            `json:"active"`
	Digital       sql.NullString  `json:"digital"`
	DigitalFilled sql.NullBool    `json:"digital_filled"`
	Image         json.RawMessage `json:"image"`
	Variants      json.RawMessage `json:"variants"`
	Created       int64           `json:"created"`
}

func (q *Queries) ListProductsPublic(ctx context.Context, arg ListProductsPublicParams) ([]ListProductsPublicRow, error) {
	rows, err := q.query(ctx, q.listProductsPublicStmt, listProductsPublic, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsPublicRow{}
	for rows.Next() {
		var i ListProductsPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brief,
			&i.Slug,
			&i.Amount,
			&i.Quantity,
			&i.HasVariants,
			&i.Active,
			&i.Digital,
			&i.DigitalFilled,
			&i.Image,
			&i.Variants,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS(SELECT 1 FROM product WHERE slug = $1 AND deleted = FALSE)
`

func (q *Queries) ProductExists(ctx context.Context, slug string) (bool, error) {
	row := q.queryRow(ctx, q.productExistsStmt, productExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const productHasSoldDigitalData = `-- name: ProductHasSoldDigitalData :one
SELECT EXISTS(
	SELECT 1 FROM digital_data dd
	INNER JOIN cart c ON dd.cart_id = c.id
	WHERE dd.product_id = $1 AND c.payment_status = 'paid'
)
`

func (q *Queries) ProductHasSoldDigitalData(ctx context.Context, productID string) (bool, error) {
	row := q.queryRow(ctx, q.productHasSoldDigitalDataStmt, productHasSoldDigitalData, productID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE product
SET deleted = TRUE, updated = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.softDeleteProductStmt, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product
SET name = $1, "desc" = $2, slug = $3, amount = $4, metadata = $5, attribute = $6, digital = $7, active = $8, updated = NOW()
WHERE id = $9
`

type UpdateProductParams struct {
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	ID        string          `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.exec(ctx, q.updateProductStmt, updateProduct,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Metadata,
		arg.Attribute,
		arg.Digital,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateProductActive = `-- name: UpdateProductActive :exec
UPDATE product
SET active = NOT active, updated = NOW()
WHERE id = $1
`

func (q *Queries) UpdateProductActive(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.updateProductActiveStmt, updateProductActive, id)
	return err
}

const updateProductFull = `-- name: UpdateProductFull :exec
UPDATE product
SET name = $1, brief = $2, "desc" = $3, slug = $4, amount = $5, quantity = $6, sku = $7,
    has_variants = $8, metadata = $9, attribute = $10, seo = $11, updated = NOW()
WHERE id = $12
`

type UpdateProductFullParams struct {
	Name        string          `json:"name"`
	Brief       string          `json:"brief"`
	Desc        string          `json:"desc"`
	Slug        string          `json:"slug"`
	Amount      string          `json:"amount"`
	Quantity    sql.NullInt32   `json:"quantity"`
	Sku         sql.NullString  `json:"sku"`
	HasVariants sql.NullBool    `json:"has_variants"`
	Metadata    json.RawMessage `json:"metadata"`
	Attribute   json.RawMessage `json:"attribute"`
	Seo         json.RawMessage `json:"seo"`
	ID          string          `json:"id"`
}

func (q *Queries) UpdateProductFull(ctx context.Context, arg UpdateProductFullParams) error {
	_, err := q.exec(ctx, q.updateProductFullStmt, updateProductFull,
		arg.Name,
		arg.Brief,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Quantity,
		arg.Sku,
		arg.HasVariants,
		arg.Metadata,
		arg.Attribute,
		arg.Seo,
		arg.ID,
	)
	return err
}

const updateProductVariant = `-- name: UpdateProductVariant :exec
UPDATE product_variant
SET sku = $2, price_surcharge = $3, quantity = $4, option_values = $5, updated = NOW()
WHERE id = $1
`

type UpdateProductVariantParams struct {
	ID             string         `json:"id"`
	Sku            sql.NullString `json:"sku"`
	PriceSurcharge sql.NullString `json:"price_surcharge"`
	Quantity       sql.NullInt32  `json:"quantity"`
	OptionValues   string         `json:"option_values"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) error {
	_, err := q.exec(ctx, q.updateProductVariantStmt, updateProductVariant,
		arg.ID,
		arg.Sku,
		arg.PriceSurcharge,
		arg.Quantity,
		arg.OptionValues,
	)
	return err
}
