// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.bulkDeleteProductImagesStmt, err = db.PrepareContext(ctx, bulkDeleteProductImages); err != nil {
		return nil, fmt.Errorf("error preparing query BulkDeleteProductImages: %w", err)
	}
	if q.checkSlugExistsStmt, err = db.PrepareContext(ctx, checkSlugExists); err != nil {
		return nil, fmt.Errorf("error preparing query CheckSlugExists: %w", err)
	}
	if q.countCartsStmt, err = db.PrepareContext(ctx, countCarts); err != nil {
		return nil, fmt.Errorf("error preparing query CountCarts: %w", err)
	}
	if q.countPagesStmt, err = db.PrepareContext(ctx, countPages); err != nil {
		return nil, fmt.Errorf("error preparing query CountPages: %w", err)
	}
	if q.countProductsStmt, err = db.PrepareContext(ctx, countProducts); err != nil {
		return nil, fmt.Errorf("error preparing query CountProducts: %w", err)
	}
	if q.createCartStmt, err = db.PrepareContext(ctx, createCart); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCart: %w", err)
	}
	if q.createCartItemStmt, err = db.PrepareContext(ctx, createCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCartItem: %w", err)
	}
	if q.createDigitalDataStmt, err = db.PrepareContext(ctx, createDigitalData); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDigitalData: %w", err)
	}
	if q.createDigitalFileStmt, err = db.PrepareContext(ctx, createDigitalFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDigitalFile: %w", err)
	}
	if q.createNewCartStmt, err = db.PrepareContext(ctx, createNewCart); err != nil {
		return nil, fmt.Errorf("error preparing query CreateNewCart: %w", err)
	}
	if q.createPageStmt, err = db.PrepareContext(ctx, createPage); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePage: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.createProductImageStmt, err = db.PrepareContext(ctx, createProductImage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProductImage: %w", err)
	}
	if q.createProductOptionStmt, err = db.PrepareContext(ctx, createProductOption); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProductOption: %w", err)
	}
	if q.createProductOptionValueStmt, err = db.PrepareContext(ctx, createProductOptionValue); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProductOptionValue: %w", err)
	}
	if q.createProductVariantStmt, err = db.PrepareContext(ctx, createProductVariant); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProductVariant: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createSettingStmt, err = db.PrepareContext(ctx, createSetting); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSetting: %w", err)
	}
	if q.createSubdomainStmt, err = db.PrepareContext(ctx, createSubdomain); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSubdomain: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteCartStmt, err = db.PrepareContext(ctx, deleteCart); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCart: %w", err)
	}
	if q.deleteCartItemStmt, err = db.PrepareContext(ctx, deleteCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCartItem: %w", err)
	}
	if q.deleteCartItemsByCartIDStmt, err = db.PrepareContext(ctx, deleteCartItemsByCartID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCartItemsByCartID: %w", err)
	}
	if q.deleteDigitalDataStmt, err = db.PrepareContext(ctx, deleteDigitalData); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDigitalData: %w", err)
	}
	if q.deleteDigitalDataByProductStmt, err = db.PrepareContext(ctx, deleteDigitalDataByProduct); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDigitalDataByProduct: %w", err)
	}
	if q.deleteDigitalFileStmt, err = db.PrepareContext(ctx, deleteDigitalFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDigitalFile: %w", err)
	}
	if q.deleteDigitalFilesStmt, err = db.PrepareContext(ctx, deleteDigitalFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteDigitalFiles: %w", err)
	}
	if q.deleteExpiredSessionsStmt, err = db.PrepareContext(ctx, deleteExpiredSessions); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredSessions: %w", err)
	}
	if q.deleteNewCartStmt, err = db.PrepareContext(ctx, deleteNewCart); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNewCart: %w", err)
	}
	if q.deletePageStmt, err = db.PrepareContext(ctx, deletePage); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePage: %w", err)
	}
	if q.deleteProductStmt, err = db.PrepareContext(ctx, deleteProduct); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProduct: %w", err)
	}
	if q.deleteProductImageStmt, err = db.PrepareContext(ctx, deleteProductImage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductImage: %w", err)
	}
	if q.deleteProductImagesStmt, err = db.PrepareContext(ctx, deleteProductImages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductImages: %w", err)
	}
	if q.deleteProductOptionStmt, err = db.PrepareContext(ctx, deleteProductOption); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductOption: %w", err)
	}
	if q.deleteProductOptionValueStmt, err = db.PrepareContext(ctx, deleteProductOptionValue); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductOptionValue: %w", err)
	}
	if q.deleteProductVariantStmt, err = db.PrepareContext(ctx, deleteProductVariant); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductVariant: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSettingStmt, err = db.PrepareContext(ctx, deleteSetting); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSetting: %w", err)
	}
	if q.deleteSubdomainStmt, err = db.PrepareContext(ctx, deleteSubdomain); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSubdomain: %w", err)
	}
	if q.getCartStmt, err = db.PrepareContext(ctx, getCart); err != nil {
		return nil, fmt.Errorf("error preparing query GetCart: %w", err)
	}
	if q.getCartByStatusAndIDStmt, err = db.PrepareContext(ctx, getCartByStatusAndID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartByStatusAndID: %w", err)
	}
	if q.getCartItemStmt, err = db.PrepareContext(ctx, getCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartItem: %w", err)
	}
	if q.getDigitalDataStmt, err = db.PrepareContext(ctx, getDigitalData); err != nil {
		return nil, fmt.Errorf("error preparing query GetDigitalData: %w", err)
	}
	if q.getDigitalDataByProductStmt, err = db.PrepareContext(ctx, getDigitalDataByProduct); err != nil {
		return nil, fmt.Errorf("error preparing query GetDigitalDataByProduct: %w", err)
	}
	if q.getDigitalFileStmt, err = db.PrepareContext(ctx, getDigitalFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetDigitalFile: %w", err)
	}
	if q.getNewCartByIDStmt, err = db.PrepareContext(ctx, getNewCartByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetNewCartByID: %w", err)
	}
	if q.getNewCartBySessionIDStmt, err = db.PrepareContext(ctx, getNewCartBySessionID); err != nil {
		return nil, fmt.Errorf("error preparing query GetNewCartBySessionID: %w", err)
	}
	if q.getPageByIDStmt, err = db.PrepareContext(ctx, getPageByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPageByID: %w", err)
	}
	if q.getPageBySlugStmt, err = db.PrepareContext(ctx, getPageBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetPageBySlug: %w", err)
	}
	if q.getPageSeoStmt, err = db.PrepareContext(ctx, getPageSeo); err != nil {
		return nil, fmt.Errorf("error preparing query GetPageSeo: %w", err)
	}
	if q.getPasswordByEmailStmt, err = db.PrepareContext(ctx, getPasswordByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetPasswordByEmail: %w", err)
	}
	if q.getPaymentSettingsStmt, err = db.PrepareContext(ctx, getPaymentSettings); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaymentSettings: %w", err)
	}
	if q.getProductByIDStmt, err = db.PrepareContext(ctx, getProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductByID: %w", err)
	}
	if q.getProductBySlugStmt, err = db.PrepareContext(ctx, getProductBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductBySlug: %w", err)
	}
	if q.getProductDetailByIDStmt, err = db.PrepareContext(ctx, getProductDetailByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductDetailByID: %w", err)
	}
	if q.getProductDetailBySlugStmt, err = db.PrepareContext(ctx, getProductDetailBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductDetailBySlug: %w", err)
	}
	if q.getProductDigitalContentStmt, err = db.PrepareContext(ctx, getProductDigitalContent); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductDigitalContent: %w", err)
	}
	if q.getProductImageStmt, err = db.PrepareContext(ctx, getProductImage); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductImage: %w", err)
	}
	if q.getProductOptionStmt, err = db.PrepareContext(ctx, getProductOption); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductOption: %w", err)
	}
	if q.getProductWithVariantsStmt, err = db.PrepareContext(ctx, getProductWithVariants); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductWithVariants: %w", err)
	}
	if q.getProductsWithImagesStmt, err = db.PrepareContext(ctx, getProductsWithImages); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductsWithImages: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.getSettingByKeyStmt, err = db.PrepareContext(ctx, getSettingByKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetSettingByKey: %w", err)
	}
	if q.getSubdomainStmt, err = db.PrepareContext(ctx, getSubdomain); err != nil {
		return nil, fmt.Errorf("error preparing query GetSubdomain: %w", err)
	}
	if q.getSubdomainByNameStmt, err = db.PrepareContext(ctx, getSubdomainByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetSubdomainByName: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.listActiveProductsStmt, err = db.PrepareContext(ctx, listActiveProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveProducts: %w", err)
	}
	if q.listAllCartsStmt, err = db.PrepareContext(ctx, listAllCarts); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllCarts: %w", err)
	}
	if q.listAllDigitalDataStmt, err = db.PrepareContext(ctx, listAllDigitalData); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllDigitalData: %w", err)
	}
	if q.listAllDigitalFilesStmt, err = db.PrepareContext(ctx, listAllDigitalFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllDigitalFiles: %w", err)
	}
	if q.listAllPagesStmt, err = db.PrepareContext(ctx, listAllPages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllPages: %w", err)
	}
	if q.listAllProductImagesStmt, err = db.PrepareContext(ctx, listAllProductImages); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllProductImages: %w", err)
	}
	if q.listAllProductsStmt, err = db.PrepareContext(ctx, listAllProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllProducts: %w", err)
	}
	if q.listAllSessionsStmt, err = db.PrepareContext(ctx, listAllSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllSessions: %w", err)
	}
	if q.listAllSubdomainsStmt, err = db.PrepareContext(ctx, listAllSubdomains); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllSubdomains: %w", err)
	}
	if q.listCartItemsStmt, err = db.PrepareContext(ctx, listCartItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListCartItems: %w", err)
	}
	if q.listCartsStmt, err = db.PrepareContext(ctx, listCarts); err != nil {
		return nil, fmt.Errorf("error preparing query ListCarts: %w", err)
	}
	if q.listDigitalDataByCartStmt, err = db.PrepareContext(ctx, listDigitalDataByCart); err != nil {
		return nil, fmt.Errorf("error preparing query ListDigitalDataByCart: %w", err)
	}
	if q.listDigitalFilesStmt, err = db.PrepareContext(ctx, listDigitalFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListDigitalFiles: %w", err)
	}
	if q.listPagesStmt, err = db.PrepareContext(ctx, listPages); err != nil {
		return nil, fmt.Errorf("error preparing query ListPages: %w", err)
	}
	if q.listPagesByPositionStmt, err = db.PrepareContext(ctx, listPagesByPosition); err != nil {
		return nil, fmt.Errorf("error preparing query ListPagesByPosition: %w", err)
	}
	if q.listProductImagesStmt, err = db.PrepareContext(ctx, listProductImages); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductImages: %w", err)
	}
	if q.listProductOptionValuesByOptionStmt, err = db.PrepareContext(ctx, listProductOptionValuesByOption); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductOptionValuesByOption: %w", err)
	}
	if q.listProductOptionsByProductStmt, err = db.PrepareContext(ctx, listProductOptionsByProduct); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductOptionsByProduct: %w", err)
	}
	if q.listProductVariantsByProductStmt, err = db.PrepareContext(ctx, listProductVariantsByProduct); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductVariantsByProduct: %w", err)
	}
	if q.listProductsStmt, err = db.PrepareContext(ctx, listProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListProducts: %w", err)
	}
	if q.listProductsPrivateStmt, err = db.PrepareContext(ctx, listProductsPrivate); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsPrivate: %w", err)
	}
	if q.listProductsPublicStmt, err = db.PrepareContext(ctx, listProductsPublic); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsPublic: %w", err)
	}
	if q.listSettingsStmt, err = db.PrepareContext(ctx, listSettings); err != nil {
		return nil, fmt.Errorf("error preparing query ListSettings: %w", err)
	}
	if q.listSubdomainsStmt, err = db.PrepareContext(ctx, listSubdomains); err != nil {
		return nil, fmt.Errorf("error preparing query ListSubdomains: %w", err)
	}
	if q.listUnassignedDigitalDataByProductStmt, err = db.PrepareContext(ctx, listUnassignedDigitalDataByProduct); err != nil {
		return nil, fmt.Errorf("error preparing query ListUnassignedDigitalDataByProduct: %w", err)
	}
	if q.pageExistsStmt, err = db.PrepareContext(ctx, pageExists); err != nil {
		return nil, fmt.Errorf("error preparing query PageExists: %w", err)
	}
	if q.productExistsStmt, err = db.PrepareContext(ctx, productExists); err != nil {
		return nil, fmt.Errorf("error preparing query ProductExists: %w", err)
	}
	if q.productHasSoldDigitalDataStmt, err = db.PrepareContext(ctx, productHasSoldDigitalData); err != nil {
		return nil, fmt.Errorf("error preparing query ProductHasSoldDigitalData: %w", err)
	}
	if q.softDeleteProductStmt, err = db.PrepareContext(ctx, softDeleteProduct); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteProduct: %w", err)
	}
	if q.subdomainExistsStmt, err = db.PrepareContext(ctx, subdomainExists); err != nil {
		return nil, fmt.Errorf("error preparing query SubdomainExists: %w", err)
	}
	if q.updateCartStmt, err = db.PrepareContext(ctx, updateCart); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCart: %w", err)
	}
	if q.updateCartItemStmt, err = db.PrepareContext(ctx, updateCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCartItem: %w", err)
	}
	if q.updateCartPaymentFieldsStmt, err = db.PrepareContext(ctx, updateCartPaymentFields); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCartPaymentFields: %w", err)
	}
	if q.updateCartPaymentIDStmt, err = db.PrepareContext(ctx, updateCartPaymentID); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCartPaymentID: %w", err)
	}
	if q.updateCartPaymentStatusStmt, err = db.PrepareContext(ctx, updateCartPaymentStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCartPaymentStatus: %w", err)
	}
	if q.updateDigitalDataStmt, err = db.PrepareContext(ctx, updateDigitalData); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateDigitalData: %w", err)
	}
	if q.updateNewCartStmt, err = db.PrepareContext(ctx, updateNewCart); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateNewCart: %w", err)
	}
	if q.updatePageStmt, err = db.PrepareContext(ctx, updatePage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePage: %w", err)
	}
	if q.updatePageActiveStmt, err = db.PrepareContext(ctx, updatePageActive); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePageActive: %w", err)
	}
	if q.updatePageContentStmt, err = db.PrepareContext(ctx, updatePageContent); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePageContent: %w", err)
	}
	if q.updatePageSeoStmt, err = db.PrepareContext(ctx, updatePageSeo); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePageSeo: %w", err)
	}
	if q.updateProductStmt, err = db.PrepareContext(ctx, updateProduct); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProduct: %w", err)
	}
	if q.updateProductActiveStmt, err = db.PrepareContext(ctx, updateProductActive); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProductActive: %w", err)
	}
	if q.updateProductFullStmt, err = db.PrepareContext(ctx, updateProductFull); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProductFull: %w", err)
	}
	if q.updateProductVariantStmt, err = db.PrepareContext(ctx, updateProductVariant); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProductVariant: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.updateSettingStmt, err = db.PrepareContext(ctx, updateSetting); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSetting: %w", err)
	}
	if q.updateSubdomainStmt, err = db.PrepareContext(ctx, updateSubdomain); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSubdomain: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.upsertSessionStmt, err = db.PrepareContext(ctx, upsertSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSession: %w", err)
	}
	if q.upsertSettingStmt, err = db.PrepareContext(ctx, upsertSetting); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSetting: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.bulkDeleteProductImagesStmt != nil {
		if cerr := q.bulkDeleteProductImagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing bulkDeleteProductImagesStmt: %w", cerr)
		}
	}
	if q.checkSlugExistsStmt != nil {
		if cerr := q.checkSlugExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkSlugExistsStmt: %w", cerr)
		}
	}
	if q.countCartsStmt != nil {
		if cerr := q.countCartsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCartsStmt: %w", cerr)
		}
	}
	if q.countPagesStmt != nil {
		if cerr := q.countPagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countPagesStmt: %w", cerr)
		}
	}
	if q.countProductsStmt != nil {
		if cerr := q.countProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductsStmt: %w", cerr)
		}
	}
	if q.createCartStmt != nil {
		if cerr := q.createCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCartStmt: %w", cerr)
		}
	}
	if q.createCartItemStmt != nil {
		if cerr := q.createCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCartItemStmt: %w", cerr)
		}
	}
	if q.createDigitalDataStmt != nil {
		if cerr := q.createDigitalDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDigitalDataStmt: %w", cerr)
		}
	}
	if q.createDigitalFileStmt != nil {
		if cerr := q.createDigitalFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDigitalFileStmt: %w", cerr)
		}
	}
	if q.createNewCartStmt != nil {
		if cerr := q.createNewCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNewCartStmt: %w", cerr)
		}
	}
	if q.createPageStmt != nil {
		if cerr := q.createPageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPageStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.createProductImageStmt != nil {
		if cerr := q.createProductImageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductImageStmt: %w", cerr)
		}
	}
	if q.createProductOptionStmt != nil {
		if cerr := q.createProductOptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductOptionStmt: %w", cerr)
		}
	}
	if q.createProductOptionValueStmt != nil {
		if cerr := q.createProductOptionValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductOptionValueStmt: %w", cerr)
		}
	}
	if q.createProductVariantStmt != nil {
		if cerr := q.createProductVariantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductVariantStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createSettingStmt != nil {
		if cerr := q.createSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSettingStmt: %w", cerr)
		}
	}
	if q.createSubdomainStmt != nil {
		if cerr := q.createSubdomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSubdomainStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteCartStmt != nil {
		if cerr := q.deleteCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCartStmt: %w", cerr)
		}
	}
	if q.deleteCartItemStmt != nil {
		if cerr := q.deleteCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCartItemStmt: %w", cerr)
		}
	}
	if q.deleteCartItemsByCartIDStmt != nil {
		if cerr := q.deleteCartItemsByCartIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCartItemsByCartIDStmt: %w", cerr)
		}
	}
	if q.deleteDigitalDataStmt != nil {
		if cerr := q.deleteDigitalDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDigitalDataStmt: %w", cerr)
		}
	}
	if q.deleteDigitalDataByProductStmt != nil {
		if cerr := q.deleteDigitalDataByProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDigitalDataByProductStmt: %w", cerr)
		}
	}
	if q.deleteDigitalFileStmt != nil {
		if cerr := q.deleteDigitalFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDigitalFileStmt: %w", cerr)
		}
	}
	if q.deleteDigitalFilesStmt != nil {
		if cerr := q.deleteDigitalFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteDigitalFilesStmt: %w", cerr)
		}
	}
	if q.deleteExpiredSessionsStmt != nil {
		if cerr := q.deleteExpiredSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredSessionsStmt: %w", cerr)
		}
	}
	if q.deleteNewCartStmt != nil {
		if cerr := q.deleteNewCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNewCartStmt: %w", cerr)
		}
	}
	if q.deletePageStmt != nil {
		if cerr := q.deletePageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePageStmt: %w", cerr)
		}
	}
	if q.deleteProductStmt != nil {
		if cerr := q.deleteProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductStmt: %w", cerr)
		}
	}
	if q.deleteProductImageStmt != nil {
		if cerr := q.deleteProductImageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductImageStmt: %w", cerr)
		}
	}
	if q.deleteProductImagesStmt != nil {
		if cerr := q.deleteProductImagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductImagesStmt: %w", cerr)
		}
	}
	if q.deleteProductOptionStmt != nil {
		if cerr := q.deleteProductOptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductOptionStmt: %w", cerr)
		}
	}
	if q.deleteProductOptionValueStmt != nil {
		if cerr := q.deleteProductOptionValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductOptionValueStmt: %w", cerr)
		}
	}
	if q.deleteProductVariantStmt != nil {
		if cerr := q.deleteProductVariantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductVariantStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSettingStmt != nil {
		if cerr := q.deleteSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSettingStmt: %w", cerr)
		}
	}
	if q.deleteSubdomainStmt != nil {
		if cerr := q.deleteSubdomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSubdomainStmt: %w", cerr)
		}
	}
	if q.getCartStmt != nil {
		if cerr := q.getCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartStmt: %w", cerr)
		}
	}
	if q.getCartByStatusAndIDStmt != nil {
		if cerr := q.getCartByStatusAndIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartByStatusAndIDStmt: %w", cerr)
		}
	}
	if q.getCartItemStmt != nil {
		if cerr := q.getCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartItemStmt: %w", cerr)
		}
	}
	if q.getDigitalDataStmt != nil {
		if cerr := q.getDigitalDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDigitalDataStmt: %w", cerr)
		}
	}
	if q.getDigitalDataByProductStmt != nil {
		if cerr := q.getDigitalDataByProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDigitalDataByProductStmt: %w", cerr)
		}
	}
	if q.getDigitalFileStmt != nil {
		if cerr := q.getDigitalFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDigitalFileStmt: %w", cerr)
		}
	}
	if q.getNewCartByIDStmt != nil {
		if cerr := q.getNewCartByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNewCartByIDStmt: %w", cerr)
		}
	}
	if q.getNewCartBySessionIDStmt != nil {
		if cerr := q.getNewCartBySessionIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNewCartBySessionIDStmt: %w", cerr)
		}
	}
	if q.getPageByIDStmt != nil {
		if cerr := q.getPageByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPageByIDStmt: %w", cerr)
		}
	}
	if q.getPageBySlugStmt != nil {
		if cerr := q.getPageBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPageBySlugStmt: %w", cerr)
		}
	}
	if q.getPageSeoStmt != nil {
		if cerr := q.getPageSeoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPageSeoStmt: %w", cerr)
		}
	}
	if q.getPasswordByEmailStmt != nil {
		if cerr := q.getPasswordByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPasswordByEmailStmt: %w", cerr)
		}
	}
	if q.getPaymentSettingsStmt != nil {
		if cerr := q.getPaymentSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaymentSettingsStmt: %w", cerr)
		}
	}
	if q.getProductByIDStmt != nil {
		if cerr := q.getProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductByIDStmt: %w", cerr)
		}
	}
	if q.getProductBySlugStmt != nil {
		if cerr := q.getProductBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductBySlugStmt: %w", cerr)
		}
	}
	if q.getProductDetailByIDStmt != nil {
		if cerr := q.getProductDetailByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductDetailByIDStmt: %w", cerr)
		}
	}
	if q.getProductDetailBySlugStmt != nil {
		if cerr := q.getProductDetailBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductDetailBySlugStmt: %w", cerr)
		}
	}
	if q.getProductDigitalContentStmt != nil {
		if cerr := q.getProductDigitalContentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductDigitalContentStmt: %w", cerr)
		}
	}
	if q.getProductImageStmt != nil {
		if cerr := q.getProductImageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductImageStmt: %w", cerr)
		}
	}
	if q.getProductOptionStmt != nil {
		if cerr := q.getProductOptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductOptionStmt: %w", cerr)
		}
	}
	if q.getProductWithVariantsStmt != nil {
		if cerr := q.getProductWithVariantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductWithVariantsStmt: %w", cerr)
		}
	}
	if q.getProductsWithImagesStmt != nil {
		if cerr := q.getProductsWithImagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductsWithImagesStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.getSettingByKeyStmt != nil {
		if cerr := q.getSettingByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSettingByKeyStmt: %w", cerr)
		}
	}
	if q.getSubdomainStmt != nil {
		if cerr := q.getSubdomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSubdomainStmt: %w", cerr)
		}
	}
	if q.getSubdomainByNameStmt != nil {
		if cerr := q.getSubdomainByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSubdomainByNameStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.listActiveProductsStmt != nil {
		if cerr := q.listActiveProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveProductsStmt: %w", cerr)
		}
	}
	if q.listAllCartsStmt != nil {
		if cerr := q.listAllCartsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllCartsStmt: %w", cerr)
		}
	}
	if q.listAllDigitalDataStmt != nil {
		if cerr := q.listAllDigitalDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllDigitalDataStmt: %w", cerr)
		}
	}
	if q.listAllDigitalFilesStmt != nil {
		if cerr := q.listAllDigitalFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllDigitalFilesStmt: %w", cerr)
		}
	}
	if q.listAllPagesStmt != nil {
		if cerr := q.listAllPagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllPagesStmt: %w", cerr)
		}
	}
	if q.listAllProductImagesStmt != nil {
		if cerr := q.listAllProductImagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllProductImagesStmt: %w", cerr)
		}
	}
	if q.listAllProductsStmt != nil {
		if cerr := q.listAllProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllProductsStmt: %w", cerr)
		}
	}
	if q.listAllSessionsStmt != nil {
		if cerr := q.listAllSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllSessionsStmt: %w", cerr)
		}
	}
	if q.listAllSubdomainsStmt != nil {
		if cerr := q.listAllSubdomainsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllSubdomainsStmt: %w", cerr)
		}
	}
	if q.listCartItemsStmt != nil {
		if cerr := q.listCartItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCartItemsStmt: %w", cerr)
		}
	}
	if q.listCartsStmt != nil {
		if cerr := q.listCartsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCartsStmt: %w", cerr)
		}
	}
	if q.listDigitalDataByCartStmt != nil {
		if cerr := q.listDigitalDataByCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDigitalDataByCartStmt: %w", cerr)
		}
	}
	if q.listDigitalFilesStmt != nil {
		if cerr := q.listDigitalFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDigitalFilesStmt: %w", cerr)
		}
	}
	if q.listPagesStmt != nil {
		if cerr := q.listPagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPagesStmt: %w", cerr)
		}
	}
	if q.listPagesByPositionStmt != nil {
		if cerr := q.listPagesByPositionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPagesByPositionStmt: %w", cerr)
		}
	}
	if q.listProductImagesStmt != nil {
		if cerr := q.listProductImagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductImagesStmt: %w", cerr)
		}
	}
	if q.listProductOptionValuesByOptionStmt != nil {
		if cerr := q.listProductOptionValuesByOptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductOptionValuesByOptionStmt: %w", cerr)
		}
	}
	if q.listProductOptionsByProductStmt != nil {
		if cerr := q.listProductOptionsByProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductOptionsByProductStmt: %w", cerr)
		}
	}
	if q.listProductVariantsByProductStmt != nil {
		if cerr := q.listProductVariantsByProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductVariantsByProductStmt: %w", cerr)
		}
	}
	if q.listProductsStmt != nil {
		if cerr := q.listProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsStmt: %w", cerr)
		}
	}
	if q.listProductsPrivateStmt != nil {
		if cerr := q.listProductsPrivateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsPrivateStmt: %w", cerr)
		}
	}
	if q.listProductsPublicStmt != nil {
		if cerr := q.listProductsPublicStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsPublicStmt: %w", cerr)
		}
	}
	if q.listSettingsStmt != nil {
		if cerr := q.listSettingsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSettingsStmt: %w", cerr)
		}
	}
	if q.listSubdomainsStmt != nil {
		if cerr := q.listSubdomainsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSubdomainsStmt: %w", cerr)
		}
	}
	if q.listUnassignedDigitalDataByProductStmt != nil {
		if cerr := q.listUnassignedDigitalDataByProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUnassignedDigitalDataByProductStmt: %w", cerr)
		}
	}
	if q.pageExistsStmt != nil {
		if cerr := q.pageExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing pageExistsStmt: %w", cerr)
		}
	}
	if q.productExistsStmt != nil {
		if cerr := q.productExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing productExistsStmt: %w", cerr)
		}
	}
	if q.productHasSoldDigitalDataStmt != nil {
		if cerr := q.productHasSoldDigitalDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing productHasSoldDigitalDataStmt: %w", cerr)
		}
	}
	if q.softDeleteProductStmt != nil {
		if cerr := q.softDeleteProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteProductStmt: %w", cerr)
		}
	}
	if q.subdomainExistsStmt != nil {
		if cerr := q.subdomainExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing subdomainExistsStmt: %w", cerr)
		}
	}
	if q.updateCartStmt != nil {
		if cerr := q.updateCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCartStmt: %w", cerr)
		}
	}
	if q.updateCartItemStmt != nil {
		if cerr := q.updateCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCartItemStmt: %w", cerr)
		}
	}
	if q.updateCartPaymentFieldsStmt != nil {
		if cerr := q.updateCartPaymentFieldsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCartPaymentFieldsStmt: %w", cerr)
		}
	}
	if q.updateCartPaymentIDStmt != nil {
		if cerr := q.updateCartPaymentIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCartPaymentIDStmt: %w", cerr)
		}
	}
	if q.updateCartPaymentStatusStmt != nil {
		if cerr := q.updateCartPaymentStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCartPaymentStatusStmt: %w", cerr)
		}
	}
	if q.updateDigitalDataStmt != nil {
		if cerr := q.updateDigitalDataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateDigitalDataStmt: %w", cerr)
		}
	}
	if q.updateNewCartStmt != nil {
		if cerr := q.updateNewCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateNewCartStmt: %w", cerr)
		}
	}
	if q.updatePageStmt != nil {
		if cerr := q.updatePageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePageStmt: %w", cerr)
		}
	}
	if q.updatePageActiveStmt != nil {
		if cerr := q.updatePageActiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePageActiveStmt: %w", cerr)
		}
	}
	if q.updatePageContentStmt != nil {
		if cerr := q.updatePageContentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePageContentStmt: %w", cerr)
		}
	}
	if q.updatePageSeoStmt != nil {
		if cerr := q.updatePageSeoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePageSeoStmt: %w", cerr)
		}
	}
	if q.updateProductStmt != nil {
		if cerr := q.updateProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStmt: %w", cerr)
		}
	}
	if q.updateProductActiveStmt != nil {
		if cerr := q.updateProductActiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductActiveStmt: %w", cerr)
		}
	}
	if q.updateProductFullStmt != nil {
		if cerr := q.updateProductFullStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductFullStmt: %w", cerr)
		}
	}
	if q.updateProductVariantStmt != nil {
		if cerr := q.updateProductVariantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductVariantStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.updateSettingStmt != nil {
		if cerr := q.updateSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSettingStmt: %w", cerr)
		}
	}
	if q.updateSubdomainStmt != nil {
		if cerr := q.updateSubdomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSubdomainStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.upsertSessionStmt != nil {
		if cerr := q.upsertSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSessionStmt: %w", cerr)
		}
	}
	if q.upsertSettingStmt != nil {
		if cerr := q.upsertSettingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSettingStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                     DBTX
	tx                                     *sql.Tx
	bulkDeleteProductImagesStmt            *sql.Stmt
	checkSlugExistsStmt                    *sql.Stmt
	countCartsStmt                         *sql.Stmt
	countPagesStmt                         *sql.Stmt
	countProductsStmt                      *sql.Stmt
	createCartStmt                         *sql.Stmt
	createCartItemStmt                     *sql.Stmt
	createDigitalDataStmt                  *sql.Stmt
	createDigitalFileStmt                  *sql.Stmt
	createNewCartStmt                      *sql.Stmt
	createPageStmt                         *sql.Stmt
	createProductStmt                      *sql.Stmt
	createProductImageStmt                 *sql.Stmt
	createProductOptionStmt                *sql.Stmt
	createProductOptionValueStmt           *sql.Stmt
	createProductVariantStmt               *sql.Stmt
	createSessionStmt                      *sql.Stmt
	createSettingStmt                      *sql.Stmt
	createSubdomainStmt                    *sql.Stmt
	createUserStmt                         *sql.Stmt
	deleteCartStmt                         *sql.Stmt
	deleteCartItemStmt                     *sql.Stmt
	deleteCartItemsByCartIDStmt            *sql.Stmt
	deleteDigitalDataStmt                  *sql.Stmt
	deleteDigitalDataByProductStmt         *sql.Stmt
	deleteDigitalFileStmt                  *sql.Stmt
	deleteDigitalFilesStmt                 *sql.Stmt
	deleteExpiredSessionsStmt              *sql.Stmt
	deleteNewCartStmt                      *sql.Stmt
	deletePageStmt                         *sql.Stmt
	deleteProductStmt                      *sql.Stmt
	deleteProductImageStmt                 *sql.Stmt
	deleteProductImagesStmt                *sql.Stmt
	deleteProductOptionStmt                *sql.Stmt
	deleteProductOptionValueStmt           *sql.Stmt
	deleteProductVariantStmt               *sql.Stmt
	deleteSessionStmt                      *sql.Stmt
	deleteSettingStmt                      *sql.Stmt
	deleteSubdomainStmt                    *sql.Stmt
	getCartStmt                            *sql.Stmt
	getCartByStatusAndIDStmt               *sql.Stmt
	getCartItemStmt                        *sql.Stmt
	getDigitalDataStmt                     *sql.Stmt
	getDigitalDataByProductStmt            *sql.Stmt
	getDigitalFileStmt                     *sql.Stmt
	getNewCartByIDStmt                     *sql.Stmt
	getNewCartBySessionIDStmt              *sql.Stmt
	getPageByIDStmt                        *sql.Stmt
	getPageBySlugStmt                      *sql.Stmt
	getPageSeoStmt                         *sql.Stmt
	getPasswordByEmailStmt                 *sql.Stmt
	getPaymentSettingsStmt                 *sql.Stmt
	getProductByIDStmt                     *sql.Stmt
	getProductBySlugStmt                   *sql.Stmt
	getProductDetailByIDStmt               *sql.Stmt
	getProductDetailBySlugStmt             *sql.Stmt
	getProductDigitalContentStmt           *sql.Stmt
	getProductImageStmt                    *sql.Stmt
	getProductOptionStmt                   *sql.Stmt
	getProductWithVariantsStmt             *sql.Stmt
	getProductsWithImagesStmt              *sql.Stmt
	getSessionStmt                         *sql.Stmt
	getSettingByKeyStmt                    *sql.Stmt
	getSubdomainStmt                       *sql.Stmt
	getSubdomainByNameStmt                 *sql.Stmt
	getUserByEmailStmt                     *sql.Stmt
	listActiveProductsStmt                 *sql.Stmt
	listAllCartsStmt                       *sql.Stmt
	listAllDigitalDataStmt                 *sql.Stmt
	listAllDigitalFilesStmt                *sql.Stmt
	listAllPagesStmt                       *sql.Stmt
	listAllProductImagesStmt               *sql.Stmt
	listAllProductsStmt                    *sql.Stmt
	listAllSessionsStmt                    *sql.Stmt
	listAllSubdomainsStmt                  *sql.Stmt
	listCartItemsStmt                      *sql.Stmt
	listCartsStmt                          *sql.Stmt
	listDigitalDataByCartStmt              *sql.Stmt
	listDigitalFilesStmt                   *sql.Stmt
	listPagesStmt                          *sql.Stmt
	listPagesByPositionStmt                *sql.Stmt
	listProductImagesStmt                  *sql.Stmt
	listProductOptionValuesByOptionStmt    *sql.Stmt
	listProductOptionsByProductStmt        *sql.Stmt
	listProductVariantsByProductStmt       *sql.Stmt
	listProductsStmt                       *sql.Stmt
	listProductsPrivateStmt                *sql.Stmt
	listProductsPublicStmt                 *sql.Stmt
	listSettingsStmt                       *sql.Stmt
	listSubdomainsStmt                     *sql.Stmt
	listUnassignedDigitalDataByProductStmt *sql.Stmt
	pageExistsStmt                         *sql.Stmt
	productExistsStmt                      *sql.Stmt
	productHasSoldDigitalDataStmt          *sql.Stmt
	softDeleteProductStmt                  *sql.Stmt
	subdomainExistsStmt                    *sql.Stmt
	updateCartStmt                         *sql.Stmt
	updateCartItemStmt                     *sql.Stmt
	updateCartPaymentFieldsStmt            *sql.Stmt
	updateCartPaymentIDStmt                *sql.Stmt
	updateCartPaymentStatusStmt            *sql.Stmt
	updateDigitalDataStmt                  *sql.Stmt
	updateNewCartStmt                      *sql.Stmt
	updatePageStmt                         *sql.Stmt
	updatePageActiveStmt                   *sql.Stmt
	updatePageContentStmt                  *sql.Stmt
	updatePageSeoStmt                      *sql.Stmt
	updateProductStmt                      *sql.Stmt
	updateProductActiveStmt                *sql.Stmt
	updateProductFullStmt                  *sql.Stmt
	updateProductVariantStmt               *sql.Stmt
	updateSessionStmt                      *sql.Stmt
	updateSettingStmt                      *sql.Stmt
	updateSubdomainStmt                    *sql.Stmt
	updateUserPasswordStmt                 *sql.Stmt
	upsertSessionStmt                      *sql.Stmt
	upsertSettingStmt                      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                     tx,
		tx:                                     tx,
		bulkDeleteProductImagesStmt:            q.bulkDeleteProductImagesStmt,
		checkSlugExistsStmt:                    q.checkSlugExistsStmt,
		countCartsStmt:                         q.countCartsStmt,
		countPagesStmt:                         q.countPagesStmt,
		countProductsStmt:                      q.countProductsStmt,
		createCartStmt:                         q.createCartStmt,
		createCartItemStmt:                     q.createCartItemStmt,
		createDigitalDataStmt:                  q.createDigitalDataStmt,
		createDigitalFileStmt:                  q.createDigitalFileStmt,
		createNewCartStmt:                      q.createNewCartStmt,
		createPageStmt:                         q.createPageStmt,
		createProductStmt:                      q.createProductStmt,
		createProductImageStmt:                 q.createProductImageStmt,
		createProductOptionStmt:                q.createProductOptionStmt,
		createProductOptionValueStmt:           q.createProductOptionValueStmt,
		createProductVariantStmt:               q.createProductVariantStmt,
		createSessionStmt:                      q.createSessionStmt,
		createSettingStmt:                      q.createSettingStmt,
		createSubdomainStmt:                    q.createSubdomainStmt,
		createUserStmt:                         q.createUserStmt,
		deleteCartStmt:                         q.deleteCartStmt,
		deleteCartItemStmt:                     q.deleteCartItemStmt,
		deleteCartItemsByCartIDStmt:            q.deleteCartItemsByCartIDStmt,
		deleteDigitalDataStmt:                  q.deleteDigitalDataStmt,
		deleteDigitalDataByProductStmt:         q.deleteDigitalDataByProductStmt,
		deleteDigitalFileStmt:                  q.deleteDigitalFileStmt,
		deleteDigitalFilesStmt:                 q.deleteDigitalFilesStmt,
		deleteExpiredSessionsStmt:              q.deleteExpiredSessionsStmt,
		deleteNewCartStmt:                      q.deleteNewCartStmt,
		deletePageStmt:                         q.deletePageStmt,
		deleteProductStmt:                      q.deleteProductStmt,
		deleteProductImageStmt:                 q.deleteProductImageStmt,
		deleteProductImagesStmt:                q.deleteProductImagesStmt,
		deleteProductOptionStmt:                q.deleteProductOptionStmt,
		deleteProductOptionValueStmt:           q.deleteProductOptionValueStmt,
		deleteProductVariantStmt:               q.deleteProductVariantStmt,
		deleteSessionStmt:                      q.deleteSessionStmt,
		deleteSettingStmt:                      q.deleteSettingStmt,
		deleteSubdomainStmt:                    q.deleteSubdomainStmt,
		getCartStmt:                            q.getCartStmt,
		getCartByStatusAndIDStmt:               q.getCartByStatusAndIDStmt,
		getCartItemStmt:                        q.getCartItemStmt,
		getDigitalDataStmt:                     q.getDigitalDataStmt,
		getDigitalDataByProductStmt:            q.getDigitalDataByProductStmt,
		getDigitalFileStmt:                     q.getDigitalFileStmt,
		getNewCartByIDStmt:                     q.getNewCartByIDStmt,
		getNewCartBySessionIDStmt:              q.getNewCartBySessionIDStmt,
		getPageByIDStmt:                        q.getPageByIDStmt,
		getPageBySlugStmt:                      q.getPageBySlugStmt,
		getPageSeoStmt:                         q.getPageSeoStmt,
		getPasswordByEmailStmt:                 q.getPasswordByEmailStmt,
		getPaymentSettingsStmt:                 q.getPaymentSettingsStmt,
		getProductByIDStmt:                     q.getProductByIDStmt,
		getProductBySlugStmt:                   q.getProductBySlugStmt,
		getProductDetailByIDStmt:               q.getProductDetailByIDStmt,
		getProductDetailBySlugStmt:             q.getProductDetailBySlugStmt,
		getProductDigitalContentStmt:           q.getProductDigitalContentStmt,
		getProductImageStmt:                    q.getProductImageStmt,
		getProductOptionStmt:                   q.getProductOptionStmt,
		getProductWithVariantsStmt:             q.getProductWithVariantsStmt,
		getProductsWithImagesStmt:              q.getProductsWithImagesStmt,
		getSessionStmt:                         q.getSessionStmt,
		getSettingByKeyStmt:                    q.getSettingByKeyStmt,
		getSubdomainStmt:                       q.getSubdomainStmt,
		getSubdomainByNameStmt:                 q.getSubdomainByNameStmt,
		getUserByEmailStmt:                     q.getUserByEmailStmt,
		listActiveProductsStmt:                 q.listActiveProductsStmt,
		listAllCartsStmt:                       q.listAllCartsStmt,
		listAllDigitalDataStmt:                 q.listAllDigitalDataStmt,
		listAllDigitalFilesStmt:                q.listAllDigitalFilesStmt,
		listAllPagesStmt:                       q.listAllPagesStmt,
		listAllProductImagesStmt:               q.listAllProductImagesStmt,
		listAllProductsStmt:                    q.listAllProductsStmt,
		listAllSessionsStmt:                    q.listAllSessionsStmt,
		listAllSubdomainsStmt:                  q.listAllSubdomainsStmt,
		listCartItemsStmt:                      q.listCartItemsStmt,
		listCartsStmt:                          q.listCartsStmt,
		listDigitalDataByCartStmt:              q.listDigitalDataByCartStmt,
		listDigitalFilesStmt:                   q.listDigitalFilesStmt,
		listPagesStmt:                          q.listPagesStmt,
		listPagesByPositionStmt:                q.listPagesByPositionStmt,
		listProductImagesStmt:                  q.listProductImagesStmt,
		listProductOptionValuesByOptionStmt:    q.listProductOptionValuesByOptionStmt,
		listProductOptionsByProductStmt:        q.listProductOptionsByProductStmt,
		listProductVariantsByProductStmt:       q.listProductVariantsByProductStmt,
		listProductsStmt:                       q.listProductsStmt,
		listProductsPrivateStmt:                q.listProductsPrivateStmt,
		listProductsPublicStmt:                 q.listProductsPublicStmt,
		listSettingsStmt:                       q.listSettingsStmt,
		listSubdomainsStmt:                     q.listSubdomainsStmt,
		listUnassignedDigitalDataByProductStmt: q.listUnassignedDigitalDataByProductStmt,
		pageExistsStmt:                         q.pageExistsStmt,
		productExistsStmt:                      q.productExistsStmt,
		productHasSoldDigitalDataStmt:          q.productHasSoldDigitalDataStmt,
		softDeleteProductStmt:                  q.softDeleteProductStmt,
		subdomainExistsStmt:                    q.subdomainExistsStmt,
		updateCartStmt:                         q.updateCartStmt,
		updateCartItemStmt:                     q.updateCartItemStmt,
		updateCartPaymentFieldsStmt:            q.updateCartPaymentFieldsStmt,
		updateCartPaymentIDStmt:                q.updateCartPaymentIDStmt,
		updateCartPaymentStatusStmt:            q.updateCartPaymentStatusStmt,
		updateDigitalDataStmt:                  q.updateDigitalDataStmt,
		updateNewCartStmt:                      q.updateNewCartStmt,
		updatePageStmt:                         q.updatePageStmt,
		updatePageActiveStmt:                   q.updatePageActiveStmt,
		updatePageContentStmt:                  q.updatePageContentStmt,
		updatePageSeoStmt:                      q.updatePageSeoStmt,
		updateProductStmt:                      q.updateProductStmt,
		updateProductActiveStmt:                q.updateProductActiveStmt,
		updateProductFullStmt:                  q.updateProductFullStmt,
		updateProductVariantStmt:               q.updateProductVariantStmt,
		updateSessionStmt:                      q.updateSessionStmt,
		updateSettingStmt:                      q.updateSettingStmt,
		updateSubdomainStmt:                    q.updateSubdomainStmt,
		updateUserPasswordStmt:                 q.updateUserPasswordStmt,
		upsertSessionStmt:                      q.upsertSessionStmt,
		upsertSettingStmt:                      q.upsertSettingStmt,
	}
}
