// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package sqlitegen

import (
	"context"
)

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customer WHERE id = ?
`

func (q *Queries) DeleteCustomer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, id)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, email, name, created, updated
FROM customer WHERE id = ? LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const insertCustomer = `-- name: InsertCustomer :one
INSERT INTO customer (id, email, name)
VALUES (?, ?, ?)
RETURNING id, email, name, created, updated
`

type InsertCustomerParams struct {
	ID    string  `json:"id"`
	Email string  `json:"email"`
	Name  *string `json:"name"`
}

func (q *Queries) InsertCustomer(ctx context.Context, arg InsertCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, insertCustomer, arg.ID, arg.Email, arg.Name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customer SET email = ?, name = ?, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCustomerParams struct {
	Email string  `json:"email"`
	Name  *string `json:"name"`
	ID    string  `json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer, arg.Email, arg.Name, arg.ID)
	return err
}
