// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: install.sql

package sqlitegen

import (
	"context"
)

const getSettingValue = `-- name: GetSettingValue :one
SELECT value
FROM setting
WHERE key = ?
LIMIT 1
`

func (q *Queries) GetSettingValue(ctx context.Context, key string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getSettingValue, key)
	var value *string
	err := row.Scan(&value)
	return value, err
}

const updateSettingValue = `-- name: UpdateSettingValue :exec
UPDATE setting
SET value = ?
WHERE key = ?
`

type UpdateSettingValueParams struct {
	Value *string `json:"value"`
	Key   string  `json:"key"`
}

func (q *Queries) UpdateSettingValue(ctx context.Context, arg UpdateSettingValueParams) error {
	_, err := q.db.ExecContext(ctx, updateSettingValue, arg.Value, arg.Key)
	return err
}
