// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"time"
)

type Cart struct {
	ID         string     `json:"id"`
	CustomerID *string    `json:"customer_id"`
	Email      *string    `json:"email"`
	Status     string     `json:"status"`
	StripeID   *string    `json:"stripe_id"`
	Amount     *float64   `json:"amount"`
	Created    *time.Time `json:"created"`
	Updated    *time.Time `json:"updated"`
}

type Customer struct {
	ID      string     `json:"id"`
	Email   string     `json:"email"`
	Name    *string    `json:"name"`
	Created *time.Time `json:"created"`
	Updated *time.Time `json:"updated"`
}

type Page struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Slug     string     `json:"slug"`
	Content  *string    `json:"content"`
	Position string     `json:"position"`
	Active   bool       `json:"active"`
	Created  *time.Time `json:"created"`
	Updated  *time.Time `json:"updated"`
}

type Product struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Desc      string     `json:"desc"`
	Slug      string     `json:"slug"`
	Amount    float64    `json:"amount"`
	Metadata  string     `json:"metadata"`
	Attribute string     `json:"attribute"`
	Digital   *string    `json:"digital"`
	Active    bool       `json:"active"`
	Deleted   bool       `json:"deleted"`
	Created   *time.Time `json:"created"`
	Updated   *time.Time `json:"updated"`
}

type Session struct {
	Key     string  `json:"key"`
	Value   *string `json:"value"`
	Expires *int64  `json:"expires"`
}

type Setting struct {
	ID    string  `json:"id"`
	Key   string  `json:"key"`
	Value *string `json:"value"`
}
