// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package sqlitegen

import (
	"context"
	"time"
)

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE product
SET deleted = TRUE, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, "desc", slug, amount, digital, active, deleted, created, updated
FROM product
WHERE id = ? AND deleted = FALSE
LIMIT 1
`

type GetProductRow struct {
	ID      string     `json:"id"`
	Name    string     `json:"name"`
	Desc    string     `json:"desc"`
	Slug    string     `json:"slug"`
	Amount  float64    `json:"amount"`
	Digital *string    `json:"digital"`
	Active  bool       `json:"active"`
	Deleted bool       `json:"deleted"`
	Created *time.Time `json:"created"`
	Updated *time.Time `json:"updated"`
}

func (q *Queries) GetProduct(ctx context.Context, id string) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO product (id, name, "desc", slug, amount, digital, active)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, "desc", slug, amount, digital, active, deleted, created, updated
`

type InsertProductParams struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Desc    string  `json:"desc"`
	Slug    string  `json:"slug"`
	Amount  float64 `json:"amount"`
	Digital *string `json:"digital"`
	Active  bool    `json:"active"`
}

type InsertProductRow struct {
	ID      string     `json:"id"`
	Name    string     `json:"name"`
	Desc    string     `json:"desc"`
	Slug    string     `json:"slug"`
	Amount  float64    `json:"amount"`
	Digital *string    `json:"digital"`
	Active  bool       `json:"active"`
	Deleted bool       `json:"deleted"`
	Created *time.Time `json:"created"`
	Updated *time.Time `json:"updated"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (InsertProductRow, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.ID,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Digital,
		arg.Active,
	)
	var i InsertProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS(SELECT 1 FROM product WHERE slug = ? AND deleted = FALSE)
`

func (q *Queries) ProductExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, productExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product
SET name = ?, "desc" = ?, slug = ?, amount = ?, digital = ?, active = ?, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateProductParams struct {
	Name    string  `json:"name"`
	Desc    string  `json:"desc"`
	Slug    string  `json:"slug"`
	Amount  float64 `json:"amount"`
	Digital *string `json:"digital"`
	Active  bool    `json:"active"`
	ID      string  `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Digital,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateProductActive = `-- name: UpdateProductActive :exec
UPDATE product
SET active = NOT active, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateProductActive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateProductActive, id)
	return err
}
