// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlitegen

import (
	"context"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM session
WHERE expires < ? AND key != ?
`

type CleanupExpiredSessionsParams struct {
	Expires *int64 `json:"expires"`
	Key     string `json:"key"`
}

func (q *Queries) CleanupExpiredSessions(ctx context.Context, arg CleanupExpiredSessionsParams) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredSessions, arg.Expires, arg.Key)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE key = ?
`

func (q *Queries) DeleteSession(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, key)
	return err
}

const getSession = `-- name: GetSession :one
SELECT key, value, expires
FROM session
WHERE key = ? AND expires > ?
LIMIT 1
`

type GetSessionParams struct {
	Key     string `json:"key"`
	Expires *int64 `json:"expires"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.Key, arg.Expires)
	var i Session
	err := row.Scan(&i.Key, &i.Value, &i.Expires)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE session
SET value = ?, expires = ?
WHERE key = ?
`

type UpdateSessionParams struct {
	Value   *string `json:"value"`
	Expires *int64  `json:"expires"`
	Key     string  `json:"key"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession, arg.Value, arg.Expires, arg.Key)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO session (key, value, expires)
VALUES (?, ?, ?)
ON CONFLICT (key) DO UPDATE
SET value = excluded.value, expires = excluded.expires
`

type UpsertSessionParams struct {
	Key     string  `json:"key"`
	Value   *string `json:"value"`
	Expires *int64  `json:"expires"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession, arg.Key, arg.Value, arg.Expires)
	return err
}
